/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Pharmacy Management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xmikova@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Order,
  UpdateOrderStatusRequest,
} from '../models';
import {
    OrderFromJSON,
    OrderToJSON,
    UpdateOrderStatusRequestFromJSON,
    UpdateOrderStatusRequestToJSON,
} from '../models';

export interface CreateOrderRequest {
    pharmacyId: string;
    order: Order;
}

export interface DeleteOrderRequest {
    pharmacyId: string;
    orderId: string;
}

export interface GetOrderRequest {
    pharmacyId: string;
    orderId: string;
}

export interface GetOrdersRequest {
    pharmacyId: string;
}

export interface UpdateOrderRequest {
    pharmacyId: string;
    orderId: string;
    order: Order;
}

export interface UpdateOrderStatusOperationRequest {
    pharmacyId: string;
    orderId: string;
    updateOrderStatusRequest: UpdateOrderStatusRequest;
}

/**
 * PharmacyOrdersApi - interface
 * 
 * @export
 * @interface PharmacyOrdersApiInterface
 */
export interface PharmacyOrdersApiInterface {
    /**
     * Use this method to create new medication order
     * @summary Creates new medication order
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {Order} order Order to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyOrdersApiInterface
     */
    createOrderRaw(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>>;

    /**
     * Use this method to create new medication order
     * Creates new medication order
     */
    createOrder(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order>;

    /**
     * Use this method to delete/cancel the specific medication order
     * @summary Cancels specific medication order
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {string} orderId pass the id of the particular order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyOrdersApiInterface
     */
    deleteOrderRaw(requestParameters: DeleteOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Use this method to delete/cancel the specific medication order
     * Cancels specific medication order
     */
    deleteOrder(requestParameters: DeleteOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * By using pharmacyId and orderId you get details of particular order
     * @summary Provides details about specific medication order
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {string} orderId pass the id of the particular order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyOrdersApiInterface
     */
    getOrderRaw(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>>;

    /**
     * By using pharmacyId and orderId you get details of particular order
     * Provides details about specific medication order
     */
    getOrder(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order>;

    /**
     * By using pharmacyId you get list of all medication orders
     * @summary Provides the list of medication orders
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyOrdersApiInterface
     */
    getOrdersRaw(requestParameters: GetOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Order>>>;

    /**
     * By using pharmacyId you get list of all medication orders
     * Provides the list of medication orders
     */
    getOrders(requestParameters: GetOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Order>>;

    /**
     * Use this method to update content of the medication order (items, etc.)
     * @summary Updates specific medication order
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {string} orderId pass the id of the particular order
     * @param {Order} order Order to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyOrdersApiInterface
     */
    updateOrderRaw(requestParameters: UpdateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>>;

    /**
     * Use this method to update content of the medication order (items, etc.)
     * Updates specific medication order
     */
    updateOrder(requestParameters: UpdateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order>;

    /**
     * Use this method to change the order status (created, confirmed, delivered, cancelled)
     * @summary Updates order status
     * @param {string} pharmacyId pass the id of the particular pharmacy
     * @param {string} orderId pass the id of the particular order
     * @param {UpdateOrderStatusRequest} updateOrderStatusRequest New order status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PharmacyOrdersApiInterface
     */
    updateOrderStatusRaw(requestParameters: UpdateOrderStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>>;

    /**
     * Use this method to change the order status (created, confirmed, delivered, cancelled)
     * Updates order status
     */
    updateOrderStatus(requestParameters: UpdateOrderStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order>;

}

/**
 * 
 */
export class PharmacyOrdersApi extends runtime.BaseAPI implements PharmacyOrdersApiInterface {

    /**
     * Use this method to create new medication order
     * Creates new medication order
     */
    async createOrderRaw(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling createOrder.');
        }

        if (requestParameters.order === null || requestParameters.order === undefined) {
            throw new runtime.RequiredError('order','Required parameter requestParameters.order was null or undefined when calling createOrder.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/pharmacy/{pharmacyId}/orders`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderToJSON(requestParameters.order),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Use this method to create new medication order
     * Creates new medication order
     */
    async createOrder(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.createOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to delete/cancel the specific medication order
     * Cancels specific medication order
     */
    async deleteOrderRaw(requestParameters: DeleteOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling deleteOrder.');
        }

        if (requestParameters.orderId === null || requestParameters.orderId === undefined) {
            throw new runtime.RequiredError('orderId','Required parameter requestParameters.orderId was null or undefined when calling deleteOrder.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/pharmacy/{pharmacyId}/orders/{orderId}`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))).replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters.orderId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this method to delete/cancel the specific medication order
     * Cancels specific medication order
     */
    async deleteOrder(requestParameters: DeleteOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrderRaw(requestParameters, initOverrides);
    }

    /**
     * By using pharmacyId and orderId you get details of particular order
     * Provides details about specific medication order
     */
    async getOrderRaw(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling getOrder.');
        }

        if (requestParameters.orderId === null || requestParameters.orderId === undefined) {
            throw new runtime.RequiredError('orderId','Required parameter requestParameters.orderId was null or undefined when calling getOrder.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/pharmacy/{pharmacyId}/orders/{orderId}`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))).replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters.orderId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * By using pharmacyId and orderId you get details of particular order
     * Provides details about specific medication order
     */
    async getOrder(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.getOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * By using pharmacyId you get list of all medication orders
     * Provides the list of medication orders
     */
    async getOrdersRaw(requestParameters: GetOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Order>>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling getOrders.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/pharmacy/{pharmacyId}/orders`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderFromJSON));
    }

    /**
     * By using pharmacyId you get list of all medication orders
     * Provides the list of medication orders
     */
    async getOrders(requestParameters: GetOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Order>> {
        const response = await this.getOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to update content of the medication order (items, etc.)
     * Updates specific medication order
     */
    async updateOrderRaw(requestParameters: UpdateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling updateOrder.');
        }

        if (requestParameters.orderId === null || requestParameters.orderId === undefined) {
            throw new runtime.RequiredError('orderId','Required parameter requestParameters.orderId was null or undefined when calling updateOrder.');
        }

        if (requestParameters.order === null || requestParameters.order === undefined) {
            throw new runtime.RequiredError('order','Required parameter requestParameters.order was null or undefined when calling updateOrder.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/pharmacy/{pharmacyId}/orders/{orderId}`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))).replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters.orderId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OrderToJSON(requestParameters.order),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Use this method to update content of the medication order (items, etc.)
     * Updates specific medication order
     */
    async updateOrder(requestParameters: UpdateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.updateOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to change the order status (created, confirmed, delivered, cancelled)
     * Updates order status
     */
    async updateOrderStatusRaw(requestParameters: UpdateOrderStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        if (requestParameters.pharmacyId === null || requestParameters.pharmacyId === undefined) {
            throw new runtime.RequiredError('pharmacyId','Required parameter requestParameters.pharmacyId was null or undefined when calling updateOrderStatus.');
        }

        if (requestParameters.orderId === null || requestParameters.orderId === undefined) {
            throw new runtime.RequiredError('orderId','Required parameter requestParameters.orderId was null or undefined when calling updateOrderStatus.');
        }

        if (requestParameters.updateOrderStatusRequest === null || requestParameters.updateOrderStatusRequest === undefined) {
            throw new runtime.RequiredError('updateOrderStatusRequest','Required parameter requestParameters.updateOrderStatusRequest was null or undefined when calling updateOrderStatus.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/pharmacy/{pharmacyId}/orders/{orderId}/status`.replace(`{${"pharmacyId"}}`, encodeURIComponent(String(requestParameters.pharmacyId))).replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters.orderId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrderStatusRequestToJSON(requestParameters.updateOrderStatusRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Use this method to change the order status (created, confirmed, delivered, cancelled)
     * Updates order status
     */
    async updateOrderStatus(requestParameters: UpdateOrderStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.updateOrderStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
