/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xmikova@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Condition } from './Condition';
import {
    ConditionFromJSON,
    ConditionFromJSONTyped,
    ConditionToJSON,
} from './Condition';
import type { WaitingListEntry } from './WaitingListEntry';
import {
    WaitingListEntryFromJSON,
    WaitingListEntryFromJSONTyped,
    WaitingListEntryToJSON,
} from './WaitingListEntry';

/**
 * 
 * @export
 * @interface Ambulance
 */
export interface Ambulance {
    /**
     * Unique identifier of the ambulance
     * @type {string}
     * @memberof Ambulance
     */
    id: string;
    /**
     * Human readable display name of the ambulance
     * @type {string}
     * @memberof Ambulance
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Ambulance
     */
    roomNumber: string;
    /**
     * 
     * @type {Array<WaitingListEntry>}
     * @memberof Ambulance
     */
    waitingList?: Array<WaitingListEntry>;
    /**
     * 
     * @type {Array<Condition>}
     * @memberof Ambulance
     */
    predefinedConditions?: Array<Condition>;
}

/**
 * Check if a given object implements the Ambulance interface.
 */
export function instanceOfAmbulance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "roomNumber" in value;

    return isInstance;
}

export function AmbulanceFromJSON(json: any): Ambulance {
    return AmbulanceFromJSONTyped(json, false);
}

export function AmbulanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ambulance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'roomNumber': json['roomNumber'],
        'waitingList': !exists(json, 'waitingList') ? undefined : ((json['waitingList'] as Array<any>).map(WaitingListEntryFromJSON)),
        'predefinedConditions': !exists(json, 'predefinedConditions') ? undefined : ((json['predefinedConditions'] as Array<any>).map(ConditionFromJSON)),
    };
}

export function AmbulanceToJSON(value?: Ambulance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'roomNumber': value.roomNumber,
        'waitingList': value.waitingList === undefined ? undefined : ((value.waitingList as Array<any>).map(WaitingListEntryToJSON)),
        'predefinedConditions': value.predefinedConditions === undefined ? undefined : ((value.predefinedConditions as Array<any>).map(ConditionToJSON)),
    };
}

