/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xmikova@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * Unique identifier of the medicine
     * @type {string}
     * @memberof OrderItem
     */
    medicineId: string;
    /**
     * Name of the medicine (for reference)
     * @type {string}
     * @memberof OrderItem
     */
    medicineName?: string;
    /**
     * Quantity to order
     * @type {number}
     * @memberof OrderItem
     */
    quantity: number;
    /**
     * Unit of measurement (tablets, bottles, boxes, etc.)
     * @type {string}
     * @memberof OrderItem
     */
    unit?: string;
    /**
     * Price per unit
     * @type {number}
     * @memberof OrderItem
     */
    unitPrice: number;
    /**
     * Total price for this item (quantity * unitPrice)
     * @type {number}
     * @memberof OrderItem
     */
    totalPrice?: number;
}

/**
 * Check if a given object implements the OrderItem interface.
 */
export function instanceOfOrderItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "medicineId" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "unitPrice" in value;

    return isInstance;
}

export function OrderItemFromJSON(json: any): OrderItem {
    return OrderItemFromJSONTyped(json, false);
}

export function OrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'medicineId': json['medicineId'],
        'medicineName': !exists(json, 'medicineName') ? undefined : json['medicineName'],
        'quantity': json['quantity'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'unitPrice': json['unitPrice'],
        'totalPrice': !exists(json, 'totalPrice') ? undefined : json['totalPrice'],
    };
}

export function OrderItemToJSON(value?: OrderItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'medicineId': value.medicineId,
        'medicineName': value.medicineName,
        'quantity': value.quantity,
        'unit': value.unit,
        'unitPrice': value.unitPrice,
        'totalPrice': value.totalPrice,
    };
}

