/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xmikova@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Ambulance,
} from '../models';
import {
    AmbulanceFromJSON,
    AmbulanceToJSON,
} from '../models';

export interface CreateAmbulanceRequest {
    ambulance: Ambulance;
}

export interface DeleteAmbulanceRequest {
    ambulanceId: string;
}

/**
 * AmbulancesApi - interface
 * 
 * @export
 * @interface AmbulancesApiInterface
 */
export interface AmbulancesApiInterface {
    /**
     * Use this method to initialize new ambulance in the system
     * @summary Saves new ambulance definition
     * @param {Ambulance} ambulance Ambulance details to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulancesApiInterface
     */
    createAmbulanceRaw(requestParameters: CreateAmbulanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ambulance>>;

    /**
     * Use this method to initialize new ambulance in the system
     * Saves new ambulance definition
     */
    createAmbulance(requestParameters: CreateAmbulanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ambulance>;

    /**
     * Use this method to delete the specific ambulance from the system.
     * @summary Deletes specific ambulance
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulancesApiInterface
     */
    deleteAmbulanceRaw(requestParameters: DeleteAmbulanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Use this method to delete the specific ambulance from the system.
     * Deletes specific ambulance
     */
    deleteAmbulance(requestParameters: DeleteAmbulanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AmbulancesApi extends runtime.BaseAPI implements AmbulancesApiInterface {

    /**
     * Use this method to initialize new ambulance in the system
     * Saves new ambulance definition
     */
    async createAmbulanceRaw(requestParameters: CreateAmbulanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Ambulance>> {
        if (requestParameters.ambulance === null || requestParameters.ambulance === undefined) {
            throw new runtime.RequiredError('ambulance','Required parameter requestParameters.ambulance was null or undefined when calling createAmbulance.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ambulance`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AmbulanceToJSON(requestParameters.ambulance),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AmbulanceFromJSON(jsonValue));
    }

    /**
     * Use this method to initialize new ambulance in the system
     * Saves new ambulance definition
     */
    async createAmbulance(requestParameters: CreateAmbulanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Ambulance> {
        const response = await this.createAmbulanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to delete the specific ambulance from the system.
     * Deletes specific ambulance
     */
    async deleteAmbulanceRaw(requestParameters: DeleteAmbulanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling deleteAmbulance.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ambulance/{ambulanceId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this method to delete the specific ambulance from the system.
     * Deletes specific ambulance
     */
    async deleteAmbulance(requestParameters: DeleteAmbulanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAmbulanceRaw(requestParameters, initOverrides);
    }

}
