/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Pharmacy Management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xmikova@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
} from './OrderItem';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
} from './OrderStatus';

/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * Unique identifier of the order
     * @type {string}
     * @memberof Order
     */
    id: string;
    /**
     * Identifier of the pharmacy placing the order
     * @type {string}
     * @memberof Order
     */
    pharmacyId: string;
    /**
     * Identifier of the supplier (optional)
     * @type {string}
     * @memberof Order
     */
    supplierId?: string;
    /**
     * List of ordered medicines
     * @type {Array<OrderItem>}
     * @memberof Order
     */
    items: Array<OrderItem>;
    /**
     * 
     * @type {OrderStatus}
     * @memberof Order
     */
    status: OrderStatus;
    /**
     * Timestamp when order was created
     * @type {Date}
     * @memberof Order
     */
    createdAt: Date;
    /**
     * Timestamp when order was last updated
     * @type {Date}
     * @memberof Order
     */
    updatedAt?: Date;
    /**
     * User ID who created the order
     * @type {string}
     * @memberof Order
     */
    createdBy?: string;
    /**
     * Additional notes for the order
     * @type {string}
     * @memberof Order
     */
    notes?: string;
}

/**
 * Check if a given object implements the Order interface.
 */
export function instanceOfOrder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "pharmacyId" in value;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pharmacyId': json['pharmacyId'],
        'supplierId': !exists(json, 'supplierId') ? undefined : json['supplierId'],
        'items': ((json['items'] as Array<any>).map(OrderItemFromJSON)),
        'status': OrderStatusFromJSON(json['status']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function OrderToJSON(value?: Order | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'pharmacyId': value.pharmacyId,
        'supplierId': value.supplierId,
        'items': ((value.items as Array<any>).map(OrderItemToJSON)),
        'status': OrderStatusToJSON(value.status),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdBy': value.createdBy,
        'notes': value.notes,
    };
}

