/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Pharmacy Management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xmikova@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
} from './OrderStatus';

/**
 * 
 * @export
 * @interface UpdateOrderStatusRequest
 */
export interface UpdateOrderStatusRequest {
    /**
     * 
     * @type {OrderStatus}
     * @memberof UpdateOrderStatusRequest
     */
    status: OrderStatus;
}

/**
 * Check if a given object implements the UpdateOrderStatusRequest interface.
 */
export function instanceOfUpdateOrderStatusRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function UpdateOrderStatusRequestFromJSON(json: any): UpdateOrderStatusRequest {
    return UpdateOrderStatusRequestFromJSONTyped(json, false);
}

export function UpdateOrderStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrderStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': OrderStatusFromJSON(json['status']),
    };
}

export function UpdateOrderStatusRequestToJSON(value?: UpdateOrderStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': OrderStatusToJSON(value.status),
    };
}

