/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PmdlPharmacyApp {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
        /**
          * @default 'pmdl-pharmacy'
         */
        "pharmacyId": string;
    }
    interface PmdlPharmacyEditor {
        "apiBase": string;
        "medicineId": string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyList {
        "apiBase": string;
        "pharmacyId": string;
    }
}
export interface PmdlPharmacyEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPmdlPharmacyEditorElement;
}
export interface PmdlPharmacyListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPmdlPharmacyListElement;
}
declare global {
    interface HTMLPmdlPharmacyAppElement extends Components.PmdlPharmacyApp, HTMLStencilElement {
    }
    var HTMLPmdlPharmacyAppElement: {
        prototype: HTMLPmdlPharmacyAppElement;
        new (): HTMLPmdlPharmacyAppElement;
    };
    interface HTMLPmdlPharmacyEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLPmdlPharmacyEditorElement extends Components.PmdlPharmacyEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPmdlPharmacyEditorElementEventMap>(type: K, listener: (this: HTMLPmdlPharmacyEditorElement, ev: PmdlPharmacyEditorCustomEvent<HTMLPmdlPharmacyEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPmdlPharmacyEditorElementEventMap>(type: K, listener: (this: HTMLPmdlPharmacyEditorElement, ev: PmdlPharmacyEditorCustomEvent<HTMLPmdlPharmacyEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPmdlPharmacyEditorElement: {
        prototype: HTMLPmdlPharmacyEditorElement;
        new (): HTMLPmdlPharmacyEditorElement;
    };
    interface HTMLPmdlPharmacyListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLPmdlPharmacyListElement extends Components.PmdlPharmacyList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPmdlPharmacyListElementEventMap>(type: K, listener: (this: HTMLPmdlPharmacyListElement, ev: PmdlPharmacyListCustomEvent<HTMLPmdlPharmacyListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPmdlPharmacyListElementEventMap>(type: K, listener: (this: HTMLPmdlPharmacyListElement, ev: PmdlPharmacyListCustomEvent<HTMLPmdlPharmacyListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPmdlPharmacyListElement: {
        prototype: HTMLPmdlPharmacyListElement;
        new (): HTMLPmdlPharmacyListElement;
    };
    interface HTMLElementTagNameMap {
        "pmdl-pharmacy-app": HTMLPmdlPharmacyAppElement;
        "pmdl-pharmacy-editor": HTMLPmdlPharmacyEditorElement;
        "pmdl-pharmacy-list": HTMLPmdlPharmacyListElement;
    }
}
declare namespace LocalJSX {
    interface PmdlPharmacyApp {
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
        /**
          * @default 'pmdl-pharmacy'
         */
        "pharmacyId"?: string;
    }
    interface PmdlPharmacyEditor {
        "apiBase"?: string;
        "medicineId"?: string;
        "onEditor-closed"?: (event: PmdlPharmacyEditorCustomEvent<string>) => void;
        "pharmacyId"?: string;
    }
    interface PmdlPharmacyList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: PmdlPharmacyListCustomEvent<string>) => void;
        "pharmacyId"?: string;
    }

    interface PmdlPharmacyAppAttributes {
        "basePath": string;
        "apiBase": string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyEditorAttributes {
        "medicineId": string;
        "pharmacyId": string;
        "apiBase": string;
    }
    interface PmdlPharmacyListAttributes {
        "apiBase": string;
        "pharmacyId": string;
    }

    interface IntrinsicElements {
        "pmdl-pharmacy-app": Omit<PmdlPharmacyApp, keyof PmdlPharmacyAppAttributes> & { [K in keyof PmdlPharmacyApp & keyof PmdlPharmacyAppAttributes]?: PmdlPharmacyApp[K] } & { [K in keyof PmdlPharmacyApp & keyof PmdlPharmacyAppAttributes as `attr:${K}`]?: PmdlPharmacyAppAttributes[K] } & { [K in keyof PmdlPharmacyApp & keyof PmdlPharmacyAppAttributes as `prop:${K}`]?: PmdlPharmacyApp[K] };
        "pmdl-pharmacy-editor": Omit<PmdlPharmacyEditor, keyof PmdlPharmacyEditorAttributes> & { [K in keyof PmdlPharmacyEditor & keyof PmdlPharmacyEditorAttributes]?: PmdlPharmacyEditor[K] } & { [K in keyof PmdlPharmacyEditor & keyof PmdlPharmacyEditorAttributes as `attr:${K}`]?: PmdlPharmacyEditorAttributes[K] } & { [K in keyof PmdlPharmacyEditor & keyof PmdlPharmacyEditorAttributes as `prop:${K}`]?: PmdlPharmacyEditor[K] };
        "pmdl-pharmacy-list": Omit<PmdlPharmacyList, keyof PmdlPharmacyListAttributes> & { [K in keyof PmdlPharmacyList & keyof PmdlPharmacyListAttributes]?: PmdlPharmacyList[K] } & { [K in keyof PmdlPharmacyList & keyof PmdlPharmacyListAttributes as `attr:${K}`]?: PmdlPharmacyListAttributes[K] } & { [K in keyof PmdlPharmacyList & keyof PmdlPharmacyListAttributes as `prop:${K}`]?: PmdlPharmacyList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pmdl-pharmacy-app": LocalJSX.IntrinsicElements["pmdl-pharmacy-app"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyAppElement>;
            "pmdl-pharmacy-editor": LocalJSX.IntrinsicElements["pmdl-pharmacy-editor"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyEditorElement>;
            "pmdl-pharmacy-list": LocalJSX.IntrinsicElements["pmdl-pharmacy-list"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyListElement>;
        }
    }
}
