/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PmdlPharmacyApp {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
        /**
          * @default 'pmdl-pharmacy'
         */
        "pharmacyId": string;
    }
    interface PmdlPharmacyEditor {
        "apiBase": string;
        "medicineId": string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyList {
        "apiBase": string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyOrderDetail {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
        "orderId": string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyOrderEditor {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
        "orderId"?: string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyOrdersList {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
        "pharmacyId": string;
    }
}
export interface PmdlPharmacyEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPmdlPharmacyEditorElement;
}
export interface PmdlPharmacyListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPmdlPharmacyListElement;
}
declare global {
    interface HTMLPmdlPharmacyAppElement extends Components.PmdlPharmacyApp, HTMLStencilElement {
    }
    var HTMLPmdlPharmacyAppElement: {
        prototype: HTMLPmdlPharmacyAppElement;
        new (): HTMLPmdlPharmacyAppElement;
    };
    interface HTMLPmdlPharmacyEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLPmdlPharmacyEditorElement extends Components.PmdlPharmacyEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPmdlPharmacyEditorElementEventMap>(type: K, listener: (this: HTMLPmdlPharmacyEditorElement, ev: PmdlPharmacyEditorCustomEvent<HTMLPmdlPharmacyEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPmdlPharmacyEditorElementEventMap>(type: K, listener: (this: HTMLPmdlPharmacyEditorElement, ev: PmdlPharmacyEditorCustomEvent<HTMLPmdlPharmacyEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPmdlPharmacyEditorElement: {
        prototype: HTMLPmdlPharmacyEditorElement;
        new (): HTMLPmdlPharmacyEditorElement;
    };
    interface HTMLPmdlPharmacyListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLPmdlPharmacyListElement extends Components.PmdlPharmacyList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPmdlPharmacyListElementEventMap>(type: K, listener: (this: HTMLPmdlPharmacyListElement, ev: PmdlPharmacyListCustomEvent<HTMLPmdlPharmacyListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPmdlPharmacyListElementEventMap>(type: K, listener: (this: HTMLPmdlPharmacyListElement, ev: PmdlPharmacyListCustomEvent<HTMLPmdlPharmacyListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPmdlPharmacyListElement: {
        prototype: HTMLPmdlPharmacyListElement;
        new (): HTMLPmdlPharmacyListElement;
    };
    interface HTMLPmdlPharmacyOrderDetailElement extends Components.PmdlPharmacyOrderDetail, HTMLStencilElement {
    }
    var HTMLPmdlPharmacyOrderDetailElement: {
        prototype: HTMLPmdlPharmacyOrderDetailElement;
        new (): HTMLPmdlPharmacyOrderDetailElement;
    };
    interface HTMLPmdlPharmacyOrderEditorElement extends Components.PmdlPharmacyOrderEditor, HTMLStencilElement {
    }
    var HTMLPmdlPharmacyOrderEditorElement: {
        prototype: HTMLPmdlPharmacyOrderEditorElement;
        new (): HTMLPmdlPharmacyOrderEditorElement;
    };
    interface HTMLPmdlPharmacyOrdersListElement extends Components.PmdlPharmacyOrdersList, HTMLStencilElement {
    }
    var HTMLPmdlPharmacyOrdersListElement: {
        prototype: HTMLPmdlPharmacyOrdersListElement;
        new (): HTMLPmdlPharmacyOrdersListElement;
    };
    interface HTMLElementTagNameMap {
        "pmdl-pharmacy-app": HTMLPmdlPharmacyAppElement;
        "pmdl-pharmacy-editor": HTMLPmdlPharmacyEditorElement;
        "pmdl-pharmacy-list": HTMLPmdlPharmacyListElement;
        "pmdl-pharmacy-order-detail": HTMLPmdlPharmacyOrderDetailElement;
        "pmdl-pharmacy-order-editor": HTMLPmdlPharmacyOrderEditorElement;
        "pmdl-pharmacy-orders-list": HTMLPmdlPharmacyOrdersListElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface PmdlPharmacyApp {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath"?: string;
        /**
          * @default 'pmdl-pharmacy'
         */
        "pharmacyId"?: string;
    }
    interface PmdlPharmacyEditor {
        "apiBase"?: string;
        "medicineId"?: string;
        "onEditor-closed"?: (event: PmdlPharmacyEditorCustomEvent<string>) => void;
        "pharmacyId"?: string;
    }
    interface PmdlPharmacyList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: PmdlPharmacyListCustomEvent<string>) => void;
        "pharmacyId"?: string;
    }
    interface PmdlPharmacyOrderDetail {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath"?: string;
        "orderId": string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyOrderEditor {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath"?: string;
        "orderId"?: string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyOrdersList {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath"?: string;
        "pharmacyId": string;
    }

    interface PmdlPharmacyAppAttributes {
        "basePath": string;
        "apiBase": string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyEditorAttributes {
        "medicineId": string;
        "pharmacyId": string;
        "apiBase": string;
    }
    interface PmdlPharmacyListAttributes {
        "apiBase": string;
        "pharmacyId": string;
    }
    interface PmdlPharmacyOrderDetailAttributes {
        "pharmacyId": string;
        "basePath": string;
        "apiBase": string;
        "orderId": string;
    }
    interface PmdlPharmacyOrderEditorAttributes {
        "pharmacyId": string;
        "basePath": string;
        "apiBase": string;
        "orderId": string;
    }
    interface PmdlPharmacyOrdersListAttributes {
        "pharmacyId": string;
        "basePath": string;
        "apiBase": string;
    }

    interface IntrinsicElements {
        "pmdl-pharmacy-app": Omit<PmdlPharmacyApp, keyof PmdlPharmacyAppAttributes> & { [K in keyof PmdlPharmacyApp & keyof PmdlPharmacyAppAttributes]?: PmdlPharmacyApp[K] } & { [K in keyof PmdlPharmacyApp & keyof PmdlPharmacyAppAttributes as `attr:${K}`]?: PmdlPharmacyAppAttributes[K] } & { [K in keyof PmdlPharmacyApp & keyof PmdlPharmacyAppAttributes as `prop:${K}`]?: PmdlPharmacyApp[K] } & OneOf<"apiBase", PmdlPharmacyApp["apiBase"], PmdlPharmacyAppAttributes["apiBase"]>;
        "pmdl-pharmacy-editor": Omit<PmdlPharmacyEditor, keyof PmdlPharmacyEditorAttributes> & { [K in keyof PmdlPharmacyEditor & keyof PmdlPharmacyEditorAttributes]?: PmdlPharmacyEditor[K] } & { [K in keyof PmdlPharmacyEditor & keyof PmdlPharmacyEditorAttributes as `attr:${K}`]?: PmdlPharmacyEditorAttributes[K] } & { [K in keyof PmdlPharmacyEditor & keyof PmdlPharmacyEditorAttributes as `prop:${K}`]?: PmdlPharmacyEditor[K] };
        "pmdl-pharmacy-list": Omit<PmdlPharmacyList, keyof PmdlPharmacyListAttributes> & { [K in keyof PmdlPharmacyList & keyof PmdlPharmacyListAttributes]?: PmdlPharmacyList[K] } & { [K in keyof PmdlPharmacyList & keyof PmdlPharmacyListAttributes as `attr:${K}`]?: PmdlPharmacyListAttributes[K] } & { [K in keyof PmdlPharmacyList & keyof PmdlPharmacyListAttributes as `prop:${K}`]?: PmdlPharmacyList[K] };
        "pmdl-pharmacy-order-detail": Omit<PmdlPharmacyOrderDetail, keyof PmdlPharmacyOrderDetailAttributes> & { [K in keyof PmdlPharmacyOrderDetail & keyof PmdlPharmacyOrderDetailAttributes]?: PmdlPharmacyOrderDetail[K] } & { [K in keyof PmdlPharmacyOrderDetail & keyof PmdlPharmacyOrderDetailAttributes as `attr:${K}`]?: PmdlPharmacyOrderDetailAttributes[K] } & { [K in keyof PmdlPharmacyOrderDetail & keyof PmdlPharmacyOrderDetailAttributes as `prop:${K}`]?: PmdlPharmacyOrderDetail[K] } & OneOf<"pharmacyId", PmdlPharmacyOrderDetail["pharmacyId"], PmdlPharmacyOrderDetailAttributes["pharmacyId"]> & OneOf<"apiBase", PmdlPharmacyOrderDetail["apiBase"], PmdlPharmacyOrderDetailAttributes["apiBase"]> & OneOf<"orderId", PmdlPharmacyOrderDetail["orderId"], PmdlPharmacyOrderDetailAttributes["orderId"]>;
        "pmdl-pharmacy-order-editor": Omit<PmdlPharmacyOrderEditor, keyof PmdlPharmacyOrderEditorAttributes> & { [K in keyof PmdlPharmacyOrderEditor & keyof PmdlPharmacyOrderEditorAttributes]?: PmdlPharmacyOrderEditor[K] } & { [K in keyof PmdlPharmacyOrderEditor & keyof PmdlPharmacyOrderEditorAttributes as `attr:${K}`]?: PmdlPharmacyOrderEditorAttributes[K] } & { [K in keyof PmdlPharmacyOrderEditor & keyof PmdlPharmacyOrderEditorAttributes as `prop:${K}`]?: PmdlPharmacyOrderEditor[K] } & OneOf<"pharmacyId", PmdlPharmacyOrderEditor["pharmacyId"], PmdlPharmacyOrderEditorAttributes["pharmacyId"]> & OneOf<"apiBase", PmdlPharmacyOrderEditor["apiBase"], PmdlPharmacyOrderEditorAttributes["apiBase"]>;
        "pmdl-pharmacy-orders-list": Omit<PmdlPharmacyOrdersList, keyof PmdlPharmacyOrdersListAttributes> & { [K in keyof PmdlPharmacyOrdersList & keyof PmdlPharmacyOrdersListAttributes]?: PmdlPharmacyOrdersList[K] } & { [K in keyof PmdlPharmacyOrdersList & keyof PmdlPharmacyOrdersListAttributes as `attr:${K}`]?: PmdlPharmacyOrdersListAttributes[K] } & { [K in keyof PmdlPharmacyOrdersList & keyof PmdlPharmacyOrdersListAttributes as `prop:${K}`]?: PmdlPharmacyOrdersList[K] } & OneOf<"pharmacyId", PmdlPharmacyOrdersList["pharmacyId"], PmdlPharmacyOrdersListAttributes["pharmacyId"]> & OneOf<"apiBase", PmdlPharmacyOrdersList["apiBase"], PmdlPharmacyOrdersListAttributes["apiBase"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pmdl-pharmacy-app": LocalJSX.IntrinsicElements["pmdl-pharmacy-app"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyAppElement>;
            "pmdl-pharmacy-editor": LocalJSX.IntrinsicElements["pmdl-pharmacy-editor"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyEditorElement>;
            "pmdl-pharmacy-list": LocalJSX.IntrinsicElements["pmdl-pharmacy-list"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyListElement>;
            "pmdl-pharmacy-order-detail": LocalJSX.IntrinsicElements["pmdl-pharmacy-order-detail"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyOrderDetailElement>;
            "pmdl-pharmacy-order-editor": LocalJSX.IntrinsicElements["pmdl-pharmacy-order-editor"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyOrderEditorElement>;
            "pmdl-pharmacy-orders-list": LocalJSX.IntrinsicElements["pmdl-pharmacy-orders-list"] & JSXBase.HTMLAttributes<HTMLPmdlPharmacyOrdersListElement>;
        }
    }
}
